# Generated by Django 4.2 on 2023-06-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=50)),
                ('img_url', models.TextField(null=True)),
                ('book_content', models.TextField(blank=True)),
                ('book_link', models.TextField(null=True)),
                ('book_genre', models.TextField(null=True)),
            ],
        ),
    ]
