# Generated by Django 4.2 on 2023-06-15 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='book_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='book.book'),
        ),
    ]
