# Generated by Django 4.2 on 2023-06-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_post_title_post_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='book_name',
            field=models.CharField(max_length=30),
        ),
    ]
