# Generated by Django 4.2.2 on 2023-06-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='book/images/%Y/%m/%d/'),
        ),
    ]
