# Generated by Django 4.2.2 on 2023-06-18 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
